go_import_path: github.com/minio/minio

language: go

addons:
  apt:
    packages:
    - shellcheck
  sonarcloud:
    organization: "newlex"
    token:
      secure: GBqsJkDCgb+5EsU9TwiqdtXq8hS4GH8yUqIbw8UtDB2fXTt+ueiI476zs4QFkpts2E1wSp9yisrnNUaZqWYqNxLeJMDDJNeWF7IITs9yqmea6ZqhxQyQIZ2B8NZxQYcJ5YZZ6u4BC8NcE9cPZ7vbADEPCzeIsUU1K/+f1aE2rz4xHsiyv8FY+3+oQq/S9z7PCLFJ6Fh6DeaS22R4k8GcNLNZBBrQGnZ3m/gP3h1Uj5ZwiEMzTgvLLEddr8bwkUA85VR6Anh6504XJpSyqCZppRYbUaRrK9YbkSan/LH8sePDk7Jl0DtwGkdrlNFFvEexP7kIxtiSsi0KR6SomJkIM8qE0M7TMBZbWq7YQf+6GKguxdMo5JOKVG+qESVq/iou/3P5LegqQjG8FNU4R49Ix2Pe1hSfkkaO1jufvlp7ls/HW2y3ZdVs+wIqINjLejWTSTtVLHZuX5maxBNjZF7iHkegqqT5KuSkrXt4gthuxHCe/SkCGYOCC6rL5yaL00WHH32mt41dE4jKPC7pNnIz48Lf3BFrPwoXl68EexAadeXh1fGWeWf+wgLgfs/IOyfWoLqz4jdEoYNHIFLiNnm1uaW/fqovJHvJolSkRxDR+CRjHfZMOXFKqKYGnUj6n8Gbe4fPawc0u8b7EQO+NVIaLmZLhQxabrPdADuNRdfji0A=

services:
  - docker

# this ensures PRs based on a local branch are not built twice
# the downside is that a PR targeting a different branch is not built
# but as a workaround you can add the branch to this list
branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
        - ARCH=x86_64
        - CGO_ENABLED=0
        - GO111MODULE=on
        - SIMPLE_CI=1
      go: 1.13.x
      script:
        - make
        - diff -au <(gofmt -s -d cmd) <(printf "")
        - diff -au <(gofmt -s -d pkg) <(printf "")
        - make test-race
        - make crosscompile
        - make verify
        - cd browser && npm install && npm run test && cd ..
        - bash -c 'shopt -s globstar; shellcheck mint/**/*.sh'

    - os: windows
      env:
        - ARCH=x86_64
        - CGO_ENABLED=0
        - GO111MODULE=on
        - SIMPLE_CI=1
      go: 1.13.x
      script:
        - go build --ldflags="$(go run buildscripts/gen-ldflags.go)" -o %GOPATH%\bin\minio.exe
        - for d in $(go list ./... | grep -v browser); do go test -v --timeout 20m "$d"; done

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'; fi

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nvm install stable ; fi

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
